### ISSUE TITLE
Bug: Not pulling correct libraries in case of big number of items on some Plex Servers

### ISSUE THREAD

**Issue by reotto613** [JurajNyiri/PlexMeetsHomeAssistant#23] opened 2021-07-13 18:33 UTC
My libraries are not showing up correctly based on the selection in the dropdown.

I can only get items to show up with selection when I choose ContinueWatching OR Recently Added.

Continue Watching is accurate except for the error which shows at the top.

Recently Added doesn't show items recently added instead it shows my Library called TV Shows.

The first two are when I select Continue Watching.

The last pic is of when Recently Added is selected.

![ContinueWatching](https://user-images.githubusercontent.com/60767748/125506329-269acdd3-c69a-443a-b6c9-1870642df406.jpg)

**Comment by JurajNyiri** [comment] 2021-07-13 18:59
You have shared your plex token with everyone who sees this issue.
Please make sure to invalidate your token by visiting your signed in devices in your plex settings and invalidating the token by removing the session from which you copied it.

As for the issue, please come to [discord](https://discord.gg/jqqz9jQXWx) where we can do some debugging and figure out whats wrong. Thank you!

**Comment by JurajNyiri** [comment] 2021-07-13 20:07
This is now a known and verified bug and fix will be released soon.

**Comment by JurajNyiri** [comment] 2021-07-13 21:01
Fixed in 2.0.9. I think the rest of the issues were caused by this unexpected error.
Let me know if you have any other issues!

**Closed by JurajNyiri** 2021-07-13 21:01 UTC
Labels: bug
