### ISSUE TITLE
Feature Request: Use maxRows in conjunction with useHorizontalScroll: 'Yes'

### ISSUE THREAD

**Issue by pavolholes** [JurajNyiri/PlexMeetsHomeAssistant#59] opened 2021-11-23 21:47 UTC
**Describe the bug**
Now when I configure useHorizontalScroll: 'Yes' then all music albums are showed only in one row.

**Expected behavior**
It would be awesome if maxRows would be considered in conjuction with useHorizontalScroll: 'Yes' and i.e. maxRows = 2 would show Horizontal scroll with music albums in 2 rows.

Option maxRows = 2 is now only applied to list of songs. Aren't you planning to use vertical scroll? So the "card" wouldn't expand height to infinite but the vertical slider would appear and you can scroll in the albums of one interpret or scroll through the list of songs of particular album.

**Checks**

[ ] I am running Home Assistant on HTTP protocol
[X] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[X] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[X] My Plex server is running on HTTPS and has a valid certificate.

**Card Configuration**
```
type: custom:plex-meets-homeassistant
protocol: https
sort: titleSort:asc
playTrailer: false
showExtras: false
showSearch: true
ip: REDACTED
token: REDACTED
port: '32400'
libraryName: Hudba
entity:
  - cast | media_player.kuchyna_google_home_mini
maxCount: ''
maxRows: '2'
useHorizontalScroll: 'Yes'
displayTitleMain: 'No'
displaySubtitleMain: 'Yes'
minWidth: '100'
minEpisodeWidth: '100'
minExpandedWidth: '100'
fontSize1: ''
fontSize2: ''
fontSize3: ''
fontSize4: '12'
minExpandedHeight: '100'
title: ''
displayType: '8'
useShuffle: 'No'
```

**Card Version**
3.3.2

**Plex Version**
4.62.1

**Comment by JurajNyiri** [comment] 2021-11-23 22:36
Duplicate of https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/53 .

**Comment by pavolholes** [comment] 2021-11-23 23:13
I don't believe it's duplicate. In the two FR I'm mentioning the same function but in different views. I'm sorry for not specifying it before. Here I was writing about the Main view, not sub view. In #53 I was refering to subview.

This FR is about showing more than one row with the horizontal slider in the first view. #53 is about implementing the horizontal view for the 2nd view (which actually expands height to infitine and breaks all other cards).

**Comment by pavlov70** [comment] 2022-01-17 16:33
Here's another vote for assigning a number of rows for horizontal scroll if possible. 

Use cases:
- wall-mounted tablets feel more natural to swipe left or right
- browser kiosk has "pull down to refresh page" feature that needs to be disabled in vertical scroll
- Frigate NVR and other cards use side scrolling. Option to match makes for more cohesive UX

Thanks for considering!

**Closed** 2022-01-17 19:27 UTC
