### ISSUE TITLE
Media items no longer scroll down in 2023.04 in iOS/Safari

### ISSUE THREAD

**Issue by pavlov70** [JurajNyiri/PlexMeetsHomeAssistant#94] opened 2023-04-14 14:13 UTC
**Describe the bug**
Media items no longer scroll down in 2023.04. Previously one could scroll down to see all items in the library. In 2023.04 items only populate the screen and one can't scroll down to see additional items. 

**To Reproduce**
1. Upgrade to 2023.04
2. View a Plex library with more items than can fit on the screen at one.
3. You can no longer scroll to see addditional items.
4. using search pulls up relevant items correctly, even if they were not showing up in the display.

**Expected behavior**
One should be able to scroll down to view additional items in library.

**Screenshots**
If this is a network error, please open network tab in your browser developer tools and paste in as much information as possible about the failing request. This will make it a lot easier to help you as soon as possible.

**Checks**
Please check below if true:

[x ] I am running Home Assistant on HTTP protocol
[ ] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[x ] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[ ] My Plex server is running on HTTPS and has a valid certificate.

**Card Configuration**
Copy and paste your card configuration. Make sure to hide token and other sensitive information.

**Card Version**
Replace this text with version of card you are using.

**Plex Version**
Replace this text with version of Plex you are using.

**Device information**
Information about device you are using to display the card. Also include browser / app information.

**Additional context**

**Comment by JurajNyiri** [comment] 2023-04-14 14:53
`scroll` event is no longer fired on scrolling, which is the cause of this bug, we will need to find out why and fix it.

**Comment by JurajNyiri** [comment] 2023-04-14 15:04
Found workaround for event - wheel event, but now `window.scrollY` is always 0.

**Comment by pavlov70** [comment] 2023-04-14 15:47
Thanks for taking a look! Please let me know if there's anything I can do to help.

**Comment by JurajNyiri** [comment] 2023-04-14 15:49
Fixed in https://github.com/JurajNyiri/PlexMeetsHomeAssistant/releases/tag/3.6.6 .

**Comment by pavlov70** [comment] 2023-04-14 16:01
Thanks for fixing it in Chrome! It still seems to be broken in Safari and the ios app even after clearing the cache. Any ideas or suggestions?

**Comment by JurajNyiri** [comment] 2023-04-14 16:16
Fixed in https://github.com/JurajNyiri/PlexMeetsHomeAssistant/releases/tag/3.6.7 .

**Closed by JurajNyiri** 2023-04-14 16:16 UTC

**Comment by pavlov70** [comment] 2023-04-14 16:20
Thank you!! I can confirm it's now working again on ios. You're the best!
    On Friday, April 14, 2023 at 12:16:30 PM EDT, Juraj Nyíri ***@***.***> wrote:  
 
 


Fixed in https://github.com/JurajNyiri/PlexMeetsHomeAssistant/releases/tag/3.6.7 .

**Comment by pavlov70** [comment] 2023-06-08 12:13
I resolved the issue for myself by reverting PlexMeetsHA to a previous version (3.6.5)

My guess is whatever change that HA made in 2023.4 that originally broke PMHA was reversed in 2023.5, and now 2023.6

Can someone please confirm the earlier version of PMHA works for them? Remember to delete your cache after updating.

**Comment by Paul-Vdp** [comment] 2023-06-08 12:29
@pavlov70 Good find ! I can confirm this retrograde also with me solves the problem.
So I guess it is an easy fix, @JurajNyiri ? ;-)

**Comment by Paul-Vdp** [comment] 2023-08-23 10:18
@JurajNyiri  May I remind you of this still unfixed problem ? It seems to me the above discussion gives all the info you need to fix it.
If not, please advise. Thx for looking into it ...

**Comment by JurajNyiri** [comment] 2023-08-23 11:31
Hi, I am really busy but PRs are welcomed, see changes that were introduced in 3.6.7 fixing the original issue: https://github.com/JurajNyiri/PlexMeetsHomeAssistant/compare/3.6.6...3.6.7

**Comment by JurajNyiri** [comment] 2023-08-23 11:49
Fixed in 3.6.8.
