### ISSUE TITLE
Feature Request: Add the ability to add in last 10 movies/tv shows added in plex

### ISSUE THREAD

**Issue by gbdavidx** [JurajNyiri/PlexMeetsHomeAssistant#2] opened 2021-05-08 05:47 UTC
Currently it shows the first 10 movies (which isnt really useful), can we add the ability for it to get the last x amount of movies added in the library? (or from tautillu)

**Comment by JurajNyiri** [comment] 2021-05-08 10:43
Duplicate of your own Feature request https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/1 .
Do not open duplicates, it will not get done sooner.

**Closed by JurajNyiri** 2021-05-08 10:43 UTC
